#include "main.h"
#include <stdlib.h>

/**
 * free_grid - frees a grid generated by alloc_grid
 * @grid: pointer to grid input
 * @height: height of grid
 *
 * Return: 0 always
 */
int free_grid(int **grid, int height)
{
	int i = 0;

	while (i < height)
	{
		free(grid[i]);
		i++;
	}
	free(grid);

	return (0);
}
